services:
  - type: web
    name: ai-video-generator
    runtime: image
    repo: https://github.com/sivateam007/ai-video-generator
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GEMINI_API_KEY
        sync: false
